### ISSUE TITLE
batch-file for EZII - OS: Windows 7 SP1 (32&64 bit)

### ISSUE THREAD

**Issue by yellow-panther** [ElliotVilhelm/IZII#1]
Hello Elliott,

I use current version **Arena GUI** www.playwitharena.com for tournaments  between WB/UCI-compatible chess engines, e.g. like https://github.com/thomasahle/sunfish/archive/master.zip (Sunfish) or https://github.com/stannous/shatranj/archive/master.zip (Shatranj) . Both are XB/WB compatible and  written in Python language.  I have installed **Python v2.7.14 for Windows** and created with **Notepad**  https://notepad-plus-plus.org/ two batch files **python -u shatranj118.py -xboard** respectively **python -u xboard.py**
[Shatranj - Sunfish Python WB.zip](https://github.com/ElliotVilhelm/IZII/files/1502942/Shatranj.-.Sunfish.Python.WB.zip)

Can you build such a batch file for IZII too and host it on GitHub, please? I am not a programmer, only tester of chess programs. This batch file then could replace the python executable and a (necessary?) commandline-parameter e.g. like xboard.

**Comment by elliotvilhelm** [comment]
I have added a batch file, run_chess.bat, one thing to mention is the Engine is built in python3 thus you will likely not be able to run with python2
