### ISSUE TITLE
Still a castling bug

### ISSUE THREAD

**Issue by rwbc** [ElliotVilhelm/IZII#2]
There are still some cases to consider for legal castling ;-)

In the game below it trid to castle after Rh8 was gone.
I guess you test now for checks the K has to cross for castling and if K and R haven't
moved yet? You should check also if the R is still there somehow.

```
[Event "RWBC"]
[Site "CAPPUCCINO"]
[Date "2018.03.26"]
[Round "2"]
[White "Ifrit_j1_5_Beta_9_9_2009 (UCI2WB)"]
[Black "Elliots's IZII"]
[Result "1-0"]
[TimeControl "30+1"]
[Number "24"]
[Annotator "4. -0.07"]

1. b3 c5 2. Bb2 Nc6 3. c4 e5 4. Nf3 {-0.07/8 0.7} Qf6 5. e4 {-0.04/7 0.7}
d5 6. cxd5 {+1.39/10 1.2} Nge7 7. dxc6 {+4.21/9 1.7} Nxc6 8. Nc3
{+4.16/7 0.8} Bg4 9. Nd5 {+4.33/8 0.8} Qd6 10. Bb5 {+4.51/8 1.7} Bxf3 11.
Qxf3 {+4.56/8 1.2} c4 12. bxc4 {+5.70/7 1.2} Rd8 13. Qh5 {+6.07/7 1.2} h6
14. c5 {+7.23/8 3} Qd7 15. Bxe5 {+6.93/6 1.0} Bxc5 16. Bxg7 {+12.54/8 0.9}
Bxf2+ 17. Kxf2 {+15.28/8 0.8} Qd6 18. Bxh8 {+16.24/7 0.8}
{Xboard: Forfeit due to invalid move: e8g8} 1-0
```

Guenther

**Comment by elliotvilhelm** [comment]
Thanks so much for the find! Looks like I was not updating the castle permissions when a rook would be taken by an opponents attack. It has been added and should be resolved.
